@host = http://localhost:3000/api/

//check if developer exists and get info
GET {{host}}dev/68f50c711e0859db59d3966e


###
POST {{host}}dev/create
Content-Type: application/json

{
  "name": "rablon",
  "email": "dev@dev.com",
  "password": "devops472"
}

