

@host = http://localhost:3000/api/
//request all the users in the user collctions
GET {{host}}user/

###
//request a spesifc user by his id
GET {{host}}user/exists/id/689c3131f84219f8f6ff1c9f
###
//add a new user
POST {{host}}user/add
Content-Type: application/json

{
    "email":"hello@123.com",
    "password":"123456Lo",
    "username":"hello"
}
###
// check to see if a user exists by his id
GET {{host}}user/exists/id/68414644d02a10f893c773c0
###

//check if the username is already taken
GET {{host}}user/exists/username/hello

###
//check if the email is already taken
GET {{host}}user/exists/email/hello@world.com

###

POST {{host}}user/login
Content-Type: application/json

{           
    "email":"hello@hello.com",
    "password":"123456Lo",
    "role":"user"
}

###



GET {{host}}user/games
###

