

@host = http://localhost:3000/api/
//request all the users in the user collctions
GET {{host}}user/ 

###
//request a spesifc user by his id
GET {{host}}user/exists/id/683e919375e6d11ac1b0b1fe

###
//add a new user
POST {{host}}user/add
Content-Type: application/json

{
    "email":"user@test.com",
    "password":"123456lo",
    "username":"userTest2"
}
###
// check to see if a user exists by his id
GET {{host}}user/exists/id/68414644d02a10f893c773c0
###

//check if the username is already taken
GET {{host}}user/exists/username/userTest

###
//check if the email is already taken
GET {{host}}user/exists/email/user@test.com

###

POST  {{host}}user/login
Content-Type: application/json

{
    "email":"user@test.com",
    "password":"123456lo",
    "role":"userTest"
}

###

GET {{host}}user/