
//request all the users in the user collctions
GET http://localhost:3000/api/user/ 

###
//request a spesifc user by his id
GET http://localhost:3000/api/user/68231a5df05ce965f5ee3136

###
//add a new user
POST http://localhost:3000/api/user/add/
Content-Type: application/json

{
    "email":"hello@hello.com",
    "password":"123wadawd",
    "username":"hello"
}
###
// check to see if a user exists by his id
GET http://localhost:3000/api/user/exists/id/68231a5df05ce965f5ee3136
###

//check if the username is already taken
GET http://localhost:3000/api/user/exists/username/hello

###

GET http://localhost:3000/api/user/exists/email/hello@bcrypt.test
